DROP TABLE IF EXISTS SELECTED_DB_TBL;
CREATE TABLE SELECTED_DB_TBL (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    db_name TEXT NOT NULL,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


DROP TABLE IF EXISTS DB_STATIC_INFO;
CREATE TABLE DB_STATIC_INFO (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    db_name TEXT NOT NULL,
    size_summary TEXT NOT NULL,
    stamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


